### PR TITLE
Disassembly performance improvements (speed, RAM)

### PR DESCRIPTION
**Pull request by zbanks**
Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

This PR is based on the work that AngheloAlf did in #477, but doesn't require adding a new python dependency. It uses `bisect` from the Python standard library. 

While working on this, I profiled `disasm.py` using [`py-spy`](https://github.com/benfred/py-spy). The biggest thing that stuck out was the list comprehensions for `vrom_variables` addresses: it was constructing a list on every `lookup_name` call.
Precomputing a `set` for these addresses makes `disasm.py` about 25-35% faster. (And the next thing that shows up in the `py-spy` flamegraph looks more marginal.)

I believe both of these changes are compatible with #465, which is also trying to improve `disasm.py`'s performance .

In both cases, the extra variables are very small (<100 kB) and don't meaningfully contribute to the overall memory usage of the app (~100 MB total).

---

### Results

The only diffs in the disassembly output were from removing symbols that overlapped with `EffTables` in `variables.txt`.

The important lines to look at are:
- `User time (seconds)` - number of CPU-seconds in the Python program (using 4 cores at 100% for 1s counts as 4s here)
- `Elapsed (wall clock) time (h:mm:ss or m:ss)` - how long the program actually took
- `Maximum resident set size (kbytes)` - amount of RAM used

These numbers show that `disasm.py` now runs on my laptop in **40% less wall clock time, and with 90% less RAM**.

Before, `6b493d3f`:
```
> /usr/bin/time --verbose python3 tools/disasm/disasm.py -j4
	Command being timed: "python3 tools/disasm/disasm.py -j4"
	User time (seconds): 98.90
	System time (seconds): 1.72
	Percent of CPU this job got: 257%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:39.15
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1149416
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 684901
	Voluntary context switches: 2906
	Involuntary context switches: 529
	Swaps: 0
	File system inputs: 16
	File system outputs: 391392
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

After `8f40452` (RAM usage commit only)
```
> /usr/bin/time --verbose python3 tools/disasm/disasm.py -j4
	Command being timed: "python3 tools/disasm/disasm.py -j4"
	User time (seconds): 95.96
	System time (seconds): 1.01
	Percent of CPU this job got: 275%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:35.17
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 112000
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 135713
	Voluntary context switches: 2909
	Involuntary context switches: 559
	Swaps: 0
	File system inputs: 0
	File system outputs: 391392
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

After `108970e` (full PR)
```
> /usr/bin/time --verbose python3 tools/disasm/disasm.py -j4
	Command being timed: "python3 tools/disasm/disasm.py -j4"
	User time (seconds): 69.81
	System time (seconds): 0.97
	Percent of CPU this job got: 298%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:23.71
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 111836
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 147166
	Voluntary context switches: 2806
	Involuntary context switches: 452
	Swaps: 0
	File system inputs: 0
	File system outputs: 391392
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

### CODE REVIEW

**Review by AngheloAlf — APPROVED** [review]

**Review by EllipticEllipsis — APPROVED** [review]
```
real    5m50.049s
user    9m36.395s
sys     2m18.724s
```
Looks okay, I tihnk, although I'm surprised by the sys time there.

**Review by jpburnett — APPROVED** [review]
_speed_

**Review by Kenix3 — APPROVED** [review]
_gotta go fast_

**Comment by zbanks** [comment]
BTW it looks like this saves about ~25s during the whole build process on `canine`, out of ~200s total (~12%).
With the decomp step originally taking ~60s, it seems like the performance there is similar to my laptop (~40% less wall clock time).
Hopefully this can help a tiny bit with some of the Jenkins queue issues?

**Pull request merged**
