### PR TITLE
Update asm-processor and diff.py

### PR DESCRIPTION
**Pull request by AngheloAlf**
Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

### CODE REVIEW

**Review by Thar0 — CHANGES_REQUESTED** [review]
As I've expressed before, I don't believe it's at all necessary to subrepo asm-processor. The only file we use from the repo that needs to be synced with upstream is the python3 script itself. Further, for organizational reasons I believe build.py should sit alongside asm-processor.py, which isn't feasible with a subrepo.

**Comment by AngheloAlf** [comment]
Why build.py can't sit there if the folder is a subrepo?

**Comment by Thar0** [comment]
It stands a high chance of being deleted when updates to the subrepo happen, and manually fixing that every time sounds worse than just manually copying the one file that we need. Not to mention, I believe subrepo folders really should just contain what's in the repo, it just doesn't seem to right to have things in those that aren't part of the associated upstream repo.

**Comment by AngheloAlf** [comment]
I see. I'll undo it then

**Review by Thar0 — APPROVED** [review]

**Review by EllipticEllipsis — APPROVED** [review]

**Review by Kenix3 — APPROVED** [review]

**Pull request merged**
