### PR TITLE
Updates readme to install dos2unix.

### PR DESCRIPTION
**Pull request by Kenix3**
Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

### CODE REVIEW

**Comment by AngheloAlf** [comment]
We have more tools that have their own requirements, like diff.py, graphovl.py, etc
Should we list all of them in the readme?
Maybe tools.md could be a better place to list that kind of stuff

**Comment by EllipticEllipsis** [comment]
The ones for essentials like diff.py should probably be listed here. And IMO it should be specified in what circumstances one would want to install dos2unix: most of us never need to touch fixle, so there's no point in us installing dos2unix.

**Comment by Kenix3** [comment]
> 
> 
> We have more tools that have their own requirements, like diff.py, graphovl.py, etc Should we list all of them in the readme? Maybe tools.md could be a better place to list that kind of stuff

Yes, we should list them all. I don't have a list available, but this was meant as a conversation starter so we can make a list.

**Comment by Kenix3** [comment]
the asm differ has these requirements:
```
python3 -m pip install --user colorama watchdog python-Levenshtein cxxfilt
```

**Comment by AngheloAlf** [comment]
I tried installing the `cxxfilt` package, but apt couldn't find it. Is it really needed?

**Comment by Kenix3** [comment]
Going to close this PR for now. We'd probably want a list of all dependencies for all tools.

**Pull request closed without merging**
