### PR TITLE
Actor effect cleanup

### PR DESCRIPTION
**Pull request by tom-overton**
I was told a while back that we prefer "effect" to "particle", so I went ahead and changed most instances of "particle". There are a few things left out here:
- Anything that ***isn't*** an actor is left untouched. I'd rather not deal with that at the moment
~~- DemoKankyo still uses `DemoKankyoParticle`, since its documentation is copied from OoT. If it's desired, I can switch that over to "particle" as well, but I'd rather float that in OoT first to make sure they're okay with it.~~ Turns out, this is new MM documentation. So I figured "why not" and replaced "particle" with "effect".

### CODE REVIEW

**Comment by engineer124** [comment]
I would look at this PR from OoT and mimic the changes made there (I think the only name I disagree with is `materialFlag`):
https://github.com/zeldaret/oot/pull/1167/files

**Comment by tom-overton** [comment]
Mimicked most of the changes in the above PR, including:
- Defines for effect count
- More consistent names for effect variables, specifically:
    - isEnabled
    - pos
    - velocity
    - accel
    - rot

I didn't like `materialFlag` either, so I'm using `isEnabled` instead. I also didn't do any *new* documentation of effect structs; I just made existing documentation consistent.

**Review by EllipticEllipsis — APPROVED** [review]
This looks much better, thanks. I agree that calling it "material" didn't explain its purpose properly, we can clearly see it just being used as a general boolean to describe whether the effect is actually being used, so seems like a good change to me.

**Comment by isghj5** [comment]
It's not up to me, but I'm against this nomenclature change.

"Effect" is already allocated to a specific class of overlays with a unique overlay pipeline different from these "Effect"s. Even if you disagreed with the use of "Particle" for one and not the other, the replacement should still be unique for clarity.

**Comment by tom-overton** [comment]
> "Effect" is already allocated to a specific class of overlays with a unique overlay pipeline different from these "Effect"s

I actually totally agree with that, but I also don't see what these would be called otherwise. Take, for example, the boss effects. What would you call `GyorgEffect`? Some of these are particulate in nature, like the bubbles or droplets, but some aren't, like the splashes. I'm not sure what you would call this that is generic enough to encompass everything that they can do. Perhaps `SpecialEffect`, since they reference `globalCtx->specialEffects`?

**Review by engineer124 — APPROVED** [review]
I'm fine with these changes but always good to keep up the discussion if an alternative way to name these are found.
fyi, `materialFlag` means something different than `isEnabled` and I don't see any use-cases of it in this PR

**Review by hensldm — APPROVED** [review]

**Review by Kenix3 — APPROVED** [review]

**Pull request merged**
