### PR TITLE
Update ZAPD subrepo

### PR DESCRIPTION
**Pull request by tom-overton**
subrepo:
  subdir:   "tools/ZAPD"
  merged:   "cb0342425"
upstream:
  origin:   "https://github.com/zeldaret/ZAPD.git"
  branch:   "master"
  commit:   "cb0342425"
git-subrepo:
  version:  "0.4.6"
  origin:   "https://github.com/ingydotnet/git-subrepo"
  commit:   "110b9eb"

I'm not sure if we can merge this one until the clang-format-14 thing is merged, given that ZAPD has already moved over to it. But from #1337, it's clear that some users are running into problems with our current ZAPD, so we'll need to upgrade eventually.

### CODE REVIEW

**Comment by hensldm** [comment]
> This fails in Jenkins because it creates 344 warnings that all look like this:
> 
> ```
> When processing file assets/xml/objects/object_ssh.xml: in input binary file object_ssh, 
> 	warning: A hardcoded pointer was found [-Whardcoded-pointer]
>                 Pointer: 0x060036C0
> ```

We probably want to pass `-Z Wno-hardcoded-pointer` to `extract_assets.py` in `make assets` for the time being. Working locally I'm not sure how to actually handle them all (for example gameplay keep has some segment 4 pointers that should just resolve to themselves but currently don't). We are also unable to use auto extracted elements in other xml files (for example object_fish uses a vtx from gameplay_keep that we would need to extract explicitly for it to show up). Though we also probably want to wait for https://github.com/NEstelami/ZAPD/pull/298 otherwise passing -Wno-hardcoded-pointer also results in an error message.

**Review by AngheloAlf — APPROVED** [review]
We don't run clang-format on subrepos like ZAPD, so it using an updated version shouldn't matter to us

**Comment by tom-overton** [comment]
> We probably want to pass `-Z Wno-hardcoded-pointer` to `extract_assets.py` in `make assets` for the time being.

Should I also pass that into the Jenkinsfile? It currently looks like this:
```
                stage('Setup MM') {
                    steps {
                        dir('mm') {
                            sh 'cp /usr/local/etc/roms/mm.us.rev1.z64 baserom.mm.us.rev1.z64'

                            // Identical to `make setup` except for copying our newer ZAPD.out into mm
                            sh 'make -C tools'
                            sh 'cp ../ZAPD.out tools/ZAPD/'
                            sh 'python3 tools/fixbaserom.py'
                            sh 'python3 tools/extract_baserom.py'
                            sh 'python3 extract_assets.py -j $(nproc)'
                        }
                    }
                }
```

**Comment by hensldm** [comment]
> > We probably want to pass `-Z Wno-hardcoded-pointer` to `extract_assets.py` in `make assets` for the time being.
> 
> Should I also pass that into the Jenkinsfile? It currently looks like this:
> ```
>                 stage('Setup MM') {
>                     steps {
>                         dir('mm') {
>                             sh 'cp /usr/local/etc/roms/mm.us.rev1.z64 baserom.mm.us.rev1.z64'
> 
>                             // Identical to `make setup` except for copying our newer ZAPD.out into mm
>                             sh 'make -C tools'
>                             sh 'cp ../ZAPD.out tools/ZAPD/'
>                             sh 'python3 tools/fixbaserom.py'
>                             sh 'python3 tools/extract_baserom.py'
>                             sh 'python3 extract_assets.py -j $(nproc)'
>                         }
>                     }
>                 }
> ```

Not that one. That is ZAPD's Jenkinsfile so should be updated on their side.

**Comment by hensldm** [comment]
FYI, the ZAPD PR fixing the warnings error message has been merged. Should be able to pull again and disable the warning with no error message.

**Comment by tom-overton** [comment]
Updated ZAPD again and disabled the warning as per @hensldm's suggestion.

**Review by hensldm — APPROVED** [review]

**Review by engineer124 — APPROVED** [review]

**Review by AngheloAlf — APPROVED** [review]

**Pull request merged**
