### PR TITLE
ClearTag Params Cleanup

### PR DESCRIPTION
**Pull request by engineer124**
With the recent push for header cleanup and splitting, I think this is a good time to bring the ClearTag params back to their header and use the header correctly.

This would also be a good time to discuss if we want param macros for spawns were the param is just the enum type i.e.
`#define CLEAR_TAG_PARAMS(type) (type)`
which would have better consistency with other param macros at the cost of being longer and trivial.

### CODE REVIEW

**Review by AngheloAlf — APPROVED** [review]
I personally like the `CLEAR_TAG_PARAMS` approach, but I can see why people may not want it. I don't have an strong opinion on it, so changing them back would be ok

**Comment by mzxrules** [comment]
the only issue I have is that it seems inconsistent to not define it as a pair of GET/SET macros. This implementation only works because PARAMS happens to not be bitpacked... other actors like EnDoor or possibly ACTORCAT_DOOR (z_map thing, not 100% how to handle) and EnSw will need that distinction

**Comment by engineer124** [comment]
So to give an example using bottles that I've been looking at:
```c
static BottleDropInfo sBottleDropInfo[] = {
    { ACTOR_EN_FISH,    FISH_PARAMS(ENFISH_0) },
    { ACTOR_OBJ_AQUA,   AQUA_PARAMS(AQUA_TYPE_COLD) },
    { ACTOR_OBJ_AQUA,   AQUA_PARAMS(AQUA_TYPE_HOT) },
    { ACTOR_EN_ZORAEGG, ZORA_EGG_PARAMS(ZORA_EGG_TYPE_11, 0) },
    { ACTOR_EN_DNP,     DEKU_PRINCESS_PARAMS(DEKU_PRINCESS_TYPE_RELEASED_FROM_BOTTLE) },
    { ACTOR_EN_MUSHI2,  ENMUSHI2_PARAMS(ENMUSHI2_0) },
    { ACTOR_EN_MUSHI2,  ENMUSHI2_PARAMS(ENMUSHI2_0) },
    { ACTOR_EN_OT,      SEAHORSE_PARAMS(SEAHORSE_TYPE_2, 0, 0) },
    { ACTOR_EN_MUSHI2,  ENMUSHI2_PARAMS(ENMUSHI2_0) },
    { ACTOR_EN_MUSHI2,  ENMUSHI2_PARAMS(ENMUSHI2_0) },
    { ACTOR_EN_MUSHI2,  ENMUSHI2_PARAMS(ENMUSHI2_0) },
};
```

The idea would be to use `SET` in the name such that:
```c
static BottleDropInfo sBottleDropInfo[] = {
    { ACTOR_EN_FISH,    FISH_SET_PARAMS(ENFISH_0) },
    { ACTOR_OBJ_AQUA,   AQUA_SET_PARAMS(AQUA_TYPE_COLD) },
    { ACTOR_OBJ_AQUA,   AQUA_SET_PARAMS(AQUA_TYPE_HOT) },
    { ACTOR_EN_ZORAEGG, ZORA_EGG_SET_PARAMS(ZORA_EGG_TYPE_11, 0) },
    { ACTOR_EN_DNP,     DEKU_PRINCESS_SET_PARAMS(DEKU_PRINCESS_TYPE_RELEASED_FROM_BOTTLE) },
    { ACTOR_EN_MUSHI2,  ENMUSHI2_SET_PARAMS(ENMUSHI2_0) },
    { ACTOR_EN_MUSHI2,  ENMUSHI2_SET_PARAMS(ENMUSHI2_0) },
    { ACTOR_EN_OT,      SEAHORSE_SET_PARAMS(SEAHORSE_TYPE_2, 0, 0) },
    { ACTOR_EN_MUSHI2,  ENMUSHI2_SET_PARAMS(ENMUSHI2_0) },
    { ACTOR_EN_MUSHI2,  ENMUSHI2_SET_PARAMS(ENMUSHI2_0) },
    { ACTOR_EN_MUSHI2,  ENMUSHI2_SET_PARAMS(ENMUSHI2_0) },
};
```

And breaking down `SEAHORSE_SET_PARAMS(SEAHORSE_TYPE_2, 0, 0)` a bit more:

the idea would be to turn:
```c
#define SEAHORSE_GET_PATH_INDEX(thisx) ((thisx)->params & 0x7F)
#define SEAHORSE_GET_SWITCH_FLAG(thisx) (((thisx)->params >> 7) & 0x7F)
#define SEAHORSE_GET_TYPE(thisx) (((thisx)->params >> 0xE) & 3)

#define SEAHORSE_PARAMS(type, pathIndex, switchFlag) (((pathIndex) & 0x7F) | (((switchFlag) & 0x7F) << 7) | (((type) & 3) << 0xE))
```
into

```c
#define SEAHORSE_GET_PATH_INDEX(thisx) ((thisx)->params & 0x7F)
#define SEAHORSE_GET_SWITCH_FLAG(thisx) (((thisx)->params >> 7) & 0x7F)
#define SEAHORSE_GET_TYPE(thisx) (((thisx)->params >> 0xE) & 3)

#define SEAHORSE_SET_PATH_INDEX(pathIndex) ((pathIndex) & 0x7F)
#define SEAHORSE_SET_SWITCH_FLAG(switchFlag) (((switchFlag) & 0x7F) << 7)
#define SEAHORSE_SET_TYPE(type) (((type) & 3) << 0xE)

#define SEAHORSE_SET_PARAMS(type, pathIndex, switchFlag) (SEAHORSE_SET_PATH_INDEX(pathIndex) | SEAHORSE_SET_SWITCH_FLAG(switchFlag) | SEAHORSE_SET_TYPE(type))
```

and for clearTag here:

```c
#define CLEAR_TAG_PARAMS(type) (type)
```

could even become:

```c
#define CLEAR_TAG_SET_TYPE(type) (type)

#define CLEAR_TAG_SET_PARAMS(type) (CLEAR_TAG_SET_TYPE(type))
```

That's your thought process?

**Comment by fig02** [comment]
Imo there only needs to be one set macro that does everything at once. No need for the individual set macros, theyd never get used outside of defining the larger set macro.
But I do agree with having `ACTOR_SET_PARAMS` and having `ACTOR_GET_X` for each individual param. This approach is already what I do in modding projects, fwiw

**Comment by engineer124** [comment]
Yeah, agree with Fig overall. The internal `_SET_` part (i.e. `SEAHORSE_SET_SWITCH_FLAG`) would have only 1 single use which would be the total `_SET_PARAMS` right below so yeah, I don't think it's really necessary.

I would also be fine with the `_SET_PARAMS` instead of `_PARAMS` only, don't have a strong preference either way. Currently only `_PARAMS` without `SET` has been used for the few instances of this macro being made, so I could clean that up here or in a follow-up PR

**Comment by hensldm** [comment]
FWIW, I prefer without `SET`, since this just bit-packs the params together, and doesn't set them to anything. For contrast see the SET weekeventreg macros, which set them to the week event reg (i.e. have an `=`). Overall I agree with even the trivial `PARAMS`, and even trivial `GET_PARAMS` that just return `this->actor.params`, though can be named better.

**Comment by fig02** [comment]
I understand that point of view, but think it makes sense when you view it as setting the params for the actor. It gets used in the actor list in the scene to give it a value, and I think `SET` makes sense in that context and goes well with `GET`.
Like, if these werent set only in data, could easily see the macro literally setting the variable. But thats just not how it happens to work

**Comment by mzxrules** [comment]
Fig might be right. Perhaps it's possible to get away with only "set all params" macros, since complex compositions like this one from z_obj_tsubo are pretty rare:

```c
//configure s32 params for spawning EN_SW (probably spawning gold skulltula)
params = (OBJ_TSUBO_P001F(&this->actor) << 2) | 0xFF01;
```


The justification I have for naming it `ACTOR_SET_PARAMS` over just `ACTOR_PARAMS` is that arguably the `ACTOR_GET_X` macros should really be just taking in a `params` not a `thisx`, since it's weird to be restricted to only accessing params stored in an Actor struct. Furthermore, there are multiple instances in the codebase where params has to be accessed without an attached instance.

**Comment by AngheloAlf** [comment]
I agree on that I would prefer the `ACTOR_GET` macros to take a `params` instead of a `thisx`, which would also be a bit more consistent with the packing macro, but I'm against to name the packing params macro as `ACTOR_SET`, because most of the time they aren't used like that.
So the general naming scheme of `ACTOR_PARAMS` and `ACTOR_GET` is fine as it is imo.

**Comment by fig02** [comment]
This packing of the params is how you set them though, its the exact opposite operation as GET.
It only doesnt set anything equal to anything else because it happens to get set via in an array of data. I dont view that as being any less of a SET than literally setting the variable directly

**Comment by AngheloAlf** [comment]
Yes, packaging is how you set them, but the usual programming convention for `GET` and `SET` is being able to set each value individually, which doesn't happen in the repo.
Taking an earlier example, you'll never see `SEAHORSE_SET_PATH_INDEX` being used individually, you see all the params being set at the same time

**Comment by fig02** [comment]
Yes I know params dont get set individually, and is why I said above that I dont think there needs to be individual macros for each param. But I still think its fine to generalize the act of packaging the params as the "set" operation, even if it doesnt set the value directly.

**Comment by hensldm** [comment]
We may just have to agree to disagree with this one. I understand your point in the sense it is meant to `SET` the params with the macro just not setting it directly. However, I think that is the fact the macro doesn't set the params directly is an important decision to make, so would still prefer without `SET`. However if OoT does decide to go with `SET` this would be kind of a stupid thing to diverge on, so would just prefer consistency in that case.

**Review by hensldm — APPROVED** [review]
Overall LGTM. Still having the discussion of `SET` vs no `SET`, but don't think it would be too bad to change at a later date if we decide to.

**Review by jpburnett — APPROVED** [review]

**Pull request merged**
