### PR TITLE
Introduce Sfx Tables

### PR DESCRIPTION
**Pull request by engineer124**
Like OoT, this PR combines the sfxId macro definitions with the sfx params defined in audio_sfx_params.c into tables broken up by sfx bank.

Using this table, enums are formed for each of the sfx and moved to `sfx.h` along with the other sfx macros. The base for each sfxId is still 0x800 (SFX_FLAG).

Documentation of these flags will be incorporated into https://github.com/zeldaret/mm/pull/798 and in documenting `code_8019AF00.c`

### CODE REVIEW

**Review by hensldm — COMMENTED** [review]
So I like the changes, but this might make it harder to find the particular sfxId you need since it now gets split amongst multiple files, and you have to know which leading number corresponds to which bank. The script should mitigate this, so probably not a big deal, just wanted to bring it up. Another idea is to prefix or add the bank number to the file name to make it easier to find.

**Comment by engineer124** [comment]
> So I like the changes, but this might make it harder to find the particular sfxId you need since it now gets split amongst multiple files, and you have to know which leading number corresponds to which bank. The script should mitigate this, so probably not a big deal, just wanted to bring it up. Another idea is to prefix or add the bank number to the file name to make it easier to find.

I've gone and added an ordered prefix to each of the file names to see if that would help

**Review by AngheloAlf — COMMENTED** [review]
This PR would break `sfxconvert.h`, right? 
I think that script reads `sfx.h` directly to get the corresponding defines. 
I guess we could try to adapt that script to make it read from the new tables, but that sounds kinda annoying to implement. The alternative would be to hardcode the defines in the script itself

**Comment by engineer124** [comment]
I hadn't really thought of `sfxconvert.py`, I've never once used that script. Presumably others use it?

Maybe I can keep the tables as is, but also keep `sfx.h` as is with the defines, and leave the new sfx enum commented out until we reach 100%?

**Review by hensldm — APPROVED** [review]

**Comment by EllipticEllipsis** [comment]
We could just keep the old header too for the time being, until actual decompilation is finished.

**Comment by engineer124** [comment]
> We could just keep the old header too for the time being, until actual decompilation is finished.



> We could just keep the old header too for the time being, until actual decompilation is finished.

The latest commit restored the old header to what it was, while updating the sfx enums to match the tables i.e. removing fake enums and oddly enough, had to add a few small sfxIds for the item bank and voice bank

**Review by AngheloAlf — APPROVED** [review]

**Review by Kenix3 — APPROVED** [review]

**Pull request merged**
