### PR TITLE
obj_visiblock OK

### PR DESCRIPTION
**Pull request by kyleburnette**

### CODE REVIEW

**Comment by isghj5** [comment]
I think you accidentally included tools/overlayhelpers/ichaindis.py

**Comment by Kenix3** [comment]
> 
> 
> I think you accidentally included tools/overlayhelpers/ichaindis.py

+1

**Review by Kenix3 — APPROVED** [review]
Looks good to me. We probably want the file permissions change to ichaindis.py.

**Review by jpburnett — APPROVED** [review]
it has 2 approved now 😄

**Pull request merged**
