### PR TITLE
NPC Tracking

### PR DESCRIPTION
**Pull request by engineer124**
See:
https://github.com/zeldaret/oot/pull/1426
and
https://github.com/zeldaret/oot/pull/1458
Much less utilized compared to its OoT counterpart

### CODE REVIEW

**Review by AngheloAlf — APPROVED** [review]
Ohhh, so this was what that code in Cremia and Romani was about. Neat

**Review by isghj5 — COMMENTED** [review]
Interesting that this seems to be a completely different system than some other NPCs use, and seems to be used by romani/cremia alone, but you said this was based on OOT code, was it used more there than in this game?

**Comment by fig02** [comment]
yes, its used all over in oot

**Review by hensldm — APPROVED** [review]
LGTM

**Review by isghj5 — APPROVED** [review]

**Pull request merged**
