### PR TITLE
Port Proposed OoT Object Docs

### PR DESCRIPTION
**Pull request by fig02**
These docs port the proposed terminology by @Dragorn421 that has been waiting in a PR in OoT for quite a while now: https://github.com/zeldaret/oot/pull/1227

By opening this PR for MM I hope to get more eyes on these proposed changes to further discussions, and try to keep the terminology in sync for both games.

This PR focuses only on changes within z_scene. There are many places in the codebase that use the "objBankIndex" term. To keep the PR palatable to review, I opted to leave that for another cleanup pass.

In OoT, the main point of discussion holding the PR up is what to call `Object_InitBank`. I opted to use `Object_InitContext` in this PR, but there are arguments against using this name. I encourage anyone reviewing this to read the whole discussion here: https://github.com/zeldaret/oot/pull/1227#discussion_r898398992

### CODE REVIEW

**Comment by hensldm** [comment]
Fwiw, I've already approved the OoT version and I still agree with it over here, but will refrain from approving this one until we get more eyes on it.

**Review by isghj5 — APPROVED** [review]
Looks good to me, the only thing that bothers me is the loss of the object area sizes define, which feels like a regression but I can't think of a good reason for those to exist after all.

**Comment by fig02** [comment]
Yeah they dont accomplish anything. The constants get used in one place, and its more helpful to see the value straight away instead of needing to open a header.

**Review by AngheloAlf — COMMENTED** [review]
As with OoT, the changes look good.

Could you add `Object_GetSlot`, `Object_SpawnPersistent` and `play->objectCtx.slots` to namefixer.py. Those functions/member seem to be the only ones that are used outside the system itself

**Review by engineer124 — APPROVED** [review]
These changes are fine with me, just have to put the docs in namefixer and make jenkins happy

**Review by AngheloAlf — APPROVED** [review]

**Comment by engineer124** [comment]
Got permission from Fig to resolve conflicts. Also added changes to `namefixer.py`. Will merge once jenkins is happy

**Pull request merged**
