### PR TITLE
libu64

### PR DESCRIPTION
**Pull request by Dragorn421**
Companion PR to OoT PR https://github.com/zeldaret/oot/pull/2267
Not sure how to document this similarly to OoT, wait for OoT's to be merged and then link to that doc? ( https://github.com/Dragorn421/oot/blob/meta_libu64/docs/libu64.md )

### CODE REVIEW

**Review by hensldm — APPROVED** [review]
Don't have too much opinion on the doc page. I kind of think we could just duplicate the full markdown file but the link does avoid the duplication which is nice.

**Comment by hensldm** [comment]
Held for documentation and https://github.com/zeldaret/oot/pull/2267

**Comment by fig02** [comment]
oot is ready to merge this fwiw, but dragorn marked it as a draft over there for some reason
@Dragorn421 was this just to hold it until mm was ready?

**Comment by Dragorn421** [comment]
> Don't have too much opinion on the doc page. I kind of think we could just duplicate the full markdown file but the link does avoid the duplication which is nice.

I think I'd rather link to it, because the document aggregates knowledge from several repos but is written from the point of view of OoT, if copied to MM it would need rewritten from MM's point of view. Or it could be rewritten to not be from OoT's point of view

in any case I'll wait for OoT's to be merged so we can work from there

**Comment by Dragorn421** [comment]
Added libu64.md linking to OoT's, comments welcome

**Review by engineer124 — APPROVED** [review]

**Pull request merged**
